backend:
  name: github
  repo: edscaylart/personal-website
  branch: master
  site_domain: https://edsonsouza.netlify.com/

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "src/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "image", name: "image", widget: "image" }
      - {
        label: "Type",
        name: "type",
        widget: "string",
        default: "project"
      }
      - { label: "Path", name: "path", widget: "string", default: "/project/" }
      - { label: "Links", name: "links", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "image", name: "thumbnail", widget: "image" }
      - {
        label: "Type",
        name: "type",
        widget: "string",
        default: "blog"
      }
      - { label: "Path", name: "path", widget: "string", default: "/blog/" }
      - { label: "Body", name: "body", widget: "markdown" }